version: "2.1"

volumes:
  pihole-config:
  dnsmasq-config:
  bsec-data:

services:
  pi-hole:
    build:
      context: .
      dockerfile: pihole.dockerfile
    restart: always
    privileged: true
    volumes:
      - 'pihole-config:/etc/pihole'
      - 'dnsmasq-config:/etc/dnsmasq.d'
    network_mode: host
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    environment:
      TZ: 'Europe/London'
      PIHOLE_DNS_: '127.0.0.1#5053'
      INTERFACE: 'eth0'
      DNSMASQ_LISTENING: 'eth0'
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: 'lan'
      REV_SERVER_TARGET: '192.168.139.1'
      REV_SERVER_CIDR: '192.168.139.0/24'
    labels:
      io.balena.features.dbus: "1"
    depends_on:
      - unbound

  unbound:
    image: klutchell/unbound-dnscrypt
    restart: always
    ports:
      - '5053:53/tcp'
      - '5053:53/udp'

  time-server:
    image: cturra/ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_TIME
    environment:
      - NTP_SERVERS=time.cloudflare.com
    dns: 192.168.139.10

  sensors:
    build: ./sensors
    volumes:
      - 'bsec-data:/data/bsec'
    privileged: true
    restart: unless-stopped
    dns: 192.168.139.10
